version: '3'
services:
  mysql-dev:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    volumes:
      - ./my-data:/var/lib/mysql
  api:
    build:
      context: ./api/
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: dev_db
      MYSQL_HOST: mysql-dev
      MYSQL_PORT: 3306
      PORT: 8080
    command: ["/app"]
    ports:
      - "8081:8080"
    restart: on-failure
  client:
    build:
      context: ./client/
      args:
        API_URL: http://localhost:8081/api/v1/
    ports:
      - "8082:3000"
    command:
      "npm run start"
    restart: on-failure
  admin:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
