version: '3'
services:
  mysql-dev:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    ports:
      - "3308:3306"
    volumes:
      - ./my-data:/var/lib/mysql
  api:
    build:
      context: ./api/
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: dev_db
      MYSQL_HOST: mysql-dev
      MYSQL_PORT: 3306
    command: ["/app"]
    volumes:
      - ./api/:/api/app
    ports:
      - "8081:8080"
    restart: on-failure
  client:
    build: ./client/
    environment:
      API_URL: http://api:8080/api/v1
    ports:
      - "8083:3000"
    command:
      "npm run start"
    restart: on-failure
  admin:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
  nginx:
    image: nginx:1.13
    ports:
      - "8088:8088"
    volumes:
      - ./nginx:/etc/nginx/conf.d
